#!/usr/bin/env sh

. ~/.bashrc

sed -i -r "s/#MYSQL_IP#/${MYSQL_IP:-localhost}/g" /usr/local/qcloud-tools/config/config.yaml
sed -i -r "s/#MYSQL_PORT#/${MYSQL_PORT:-3306}/g" /usr/local/qcloud-tools/config/config.yaml
sed -i -r "s/#MYSQL_DATABASE#/${MYSQL_DATABASE:-qcloud-tools}/g" /usr/local/qcloud-tools/config/config.yaml
sed -i -r "s/#MYSQL_USERNAME#/${MYSQL_USERNAME:-db_qcloud}/g" /usr/local/qcloud-tools/config/config.yaml
sed -i -r "s/#MYSQL_PASSWORD#/${MYSQL_PASSWORD:-58117aec3b3252a97be0}/g" /usr/local/qcloud-tools/config/config.yaml

sed -i -r "s/#OPEN_MONITOR#/${MYSQL_PASSWORD:-false}/g" /usr/local/qcloud-tools/config/config.yaml

sed -i -r "s/#HTTP_PORT#/${HTTP_PORT:-80}/g" /usr/local/qcloud-tools/config/config.yaml

cd /usr/local/qcloud-tools/

./cert-monitor

./cert-http