db:
  host: "#MYSQL_IP#"
  port: #MYSQL_PORT#
  database: "#MYSQL_DATABASE#"
  user: "#MYSQL_USERNAME#"
  password: "#MYSQL_PASSWORD#"
log:
  name: "qcloud-tool"
  path: ""
switch:
  openMonitor: #OPEN_MONITOR#
  openHttp: #OPEN_HTTP#
http:
  port: #HTTP_PORT#